services:
  app:
    build: .
    ports:
      - "50051:50051"
    environment:
      - APP_ENV=docker
      - CONFIG_PATH=/configs/config-docker.yaml
      - GRPC_PORT=50051
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_ADDR=redis:6379
      - FILE_STORE_PATH=/storage
    networks:
      - app-network
    volumes:
      - ./.env:/.env
      - ./configs:/configs
      - ./storage:/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5


  redis:
    image: redis:7-alpine
    networks:
      - app-network
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  redisdata:

networks:
  app-network:
    driver: bridge
