env: "docker"

grpc_port: "50051"
storage_path: "/storage"

http_server:
  address: "0.0.0.0:8080"
  timeout: 5s
  idle_timeout: 60s

database:
  user: "postgres"
  password: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

redis:
  addr: "redis:6379"
  password: ""
  db: 0
